#!/usr/bin/env python3

import argparse
import subprocess

# Copied from SO http://stackoverflow.com/questions/287871/print-in-terminal-with-colors-using-python
OKBLUE = '\033[94m'
OKGREEN = '\033[92m'
WARNING = '\033[93m'
FAIL = '\033[91m'
ENDC = '\033[0m'


def get_commits():
    p = subprocess.Popen(['git', '--no-pager', 'log', '--decorate=short',
                          '--pretty=format:%h;%ci;%an;%s', '--all'],
                         stdout=subprocess.PIPE)
    return p.stdout.readlines()


def get_branches_containing_commit(revision):
    p = subprocess.Popen(['git', 'branch', '-r', '--contains', revision],
                         stdout=subprocess.PIPE)
    return p.stdout.readlines()


def main():
    try:
        for line in get_commits():
            data = line.split(b';')
            revision = data[0]
            creation_time = data[1][:19]
            author = data[2].replace(b'\n', b'')
            message = '%s...' % data[3].replace(b'\n', b'')[:60]
            branches = get_branches_containing_commit(revision)
            if len(branches) > 0:
                continue
            print(creation_time, FAIL, revision, ENDC, OKBLUE, author, ENDC, message)
    except KeyboardInterrupt:
        print("Terminated")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Script to check for potential'
                                                 ' missing commits.')
    args = parser.parse_args()
    main()
